### PR TITLE
Postgres: Add a check to determine if table already exists to elide CREATE query

### LINKED ISSUE #266: postgres: ensureVersionTable() is a little more brittle with BDR than mattes/migrate
**Describe the Bug**
postgres BDR will not allow any DDL statement unless the entire cluster is up and healthy.  This includes CREATE TABLE IF NOT EXISTS statements.  So if executing the migrate tool against a BDR database where some nodes are not up, the migrate tool will always fail in ensureVersionTable().

In mattes/migrate, ensureVersionTable() succeeds even when the BDR cluster is unhealthy, because it used to run two queries: 1. a read query to see if the schema_migrations table exists (not a DDL statement, will succeed even if the BDR cluster is unhealthy), then 2. CREATE TABLE only when needed.

It would be odd to run migrate against a database in this state, because if there were any migrations to run, the migrations themselves would likely also fail.  But in our system, our microservices run migrate every time their containers boot up.  In unhealthy BDR clusters, typically, there are no pending migrations to run (because we are not typically in the middle of a system upgrade at the same time as dealing with a cluster outage), so with mattes/migrate, our `migrate` call is a no-op, and the service proceeds to boot up.

I was wondering if the maintainers would be amenable to PR which adds the `SELECT COUNT(1) FROM information_schema.tables WHERE table_name = $1 AND table_schema = (SELECT current_schema()) LIMIT 1` query back into ensureVersionTable(), and avoids the "CREATE TABLE" statement when unnecessary.

**Migrate Version**
v4.5.0

### PR DESCRIPTION
**Pull request by testtest959**
This PR adds a check in `ensureVersionTable()` in order to prevent a CREATE query which may fail for read only users. As a result, read only users will be able to query the schema version.

Closes #266

### CODE REVIEW

**Comment by testtest959** [comment]
Not too sure why it's timing out, will try again. Looks like a circleci issue

**Comment by testtest959** [comment]
Ok, it looks like this is outside my control. Will just leave it for now

File: database/postgres/postgres_test.go [hunk 1]
```diff
@@ -310,6 +310,159 @@ func TestWithSchema(t *testing.T) {
...
+				return
+			}
+			if err := d2.Close(); err != nil {
+				t.Fatal(err)
+			}
+		}()
+
+		var e *database.Error
+		if !errors.As(err, &e) || err == nil {
+			t.Fatal("Unexpected error, want permission denied error. Got: ", err)
```
Comment (dhui) [inline database/postgres/postgres_test.go:374]: Is the permission denied error exposed? e.g. a [postgres error code](https://www.postgresql.org/docs/current/errcodes-appendix.html)

**Review by dhui — CHANGES_REQUESTED** [review]
Thanks for the PR and tests!!

File: database/postgres/postgres_test.go (hunk 1 above)
Comment (testtest959) [reply database/postgres/postgres_test.go:374]: Yup, but we have to parse the error string to do it. Made the change!

File: database/postgres/postgres_test.go [hunk 2]
```diff
@@ -310,6 +310,159 @@ func TestWithSchema(t *testing.T) {
...
+
+		defer func() {
+			if err := d.Close(); err != nil {
+				t.Error(err)
+			}
+		}()
+
+		// create user who is not the owner. Although we're concatenating strings in an sql statement it should be fine
+		// since this is a test environment and we're not expecting to the pgPassword to be malicious
+		if err := d.Run(strings.NewReader("CREATE USER not_owner WITH ENCRYPTED PASSWORD '" + pgPassword + "'")); err != nil {
```
[the remark this answers is not in the document]
Comment (testtest959) [reply database/postgres/postgres_test.go:339]: Awesome! That makes this a lot cleaner

File: database/pgx/pgx_test.go [hunk 3]
```diff
@@ -309,6 +318,141 @@ func TestWithSchema(t *testing.T) {
...
+				t.Fatal(err)
+			}
+		}()
+
+		var e *database.Error
+		if !errors.As(err, &e) || err == nil {
+			t.Fatal("Unexpected error, want permission denied error. Got: ", err)
+		}
+
+		if strings.Contains(e.Err, "permission denied for schema barfoo") {
```
Comment (dhui) [inline database/pgx/pgx_test.go:373]: Shouldn't this be `!strings.Contains()`?

File: database/postgres/postgres_test.go [hunk 4]
```diff
@@ -310,6 +318,141 @@ func TestWithSchema(t *testing.T) {
...
+				t.Fatal(err)
+			}
+		}()
+
+		var e *database.Error
+		if !errors.As(err, &e) || err == nil {
+			t.Fatal("Unexpected error, want permission denied error. Got: ", err)
+		}
+
+		if strings.Contains(e.Err, "permission denied for schema barfoo") {
```
Comment (dhui) [inline database/postgres/postgres_test.go:373]: Ditto with `!strings.Contains()`

**Review by dhui — COMMENTED** [review]
Thanks for addressing my feedback. The test setup code looks much cleaner now!

Also, thanks for also updating the pgx driver!

File: database/pgx/pgx_test.go (hunk 3 above)
Comment (testtest959) [reply database/pgx/pgx_test.go]: Nice catch, the assert was broken before then

**Review by dhui — APPROVED** [review]
