### PR TITLE
postgres: Make `ensureVersionTable` atomic

### LINKED ISSUE #55: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
We hit an error in our tests similar to #235 
```
pq: duplicate key value violates unique constraint "pg_type_typname_nsp_index" in line 0: CREATE TABLE "schema_migrations" (version bigint not null primary key, dirty boolean not null)
```
What bothers me is that this is not `ErrLocked`. So it seems like the lock does not work as expected.
Or do I get it wrong?
We use Postgres and we call it like this
```go
func updateSchema(db *sqlx.DB) error {
	driver, err := migratepg.WithInstance(db.DB, &migratepg.Config{})
	if err != nil {
		return err
	}
	m, err := migrate.NewWithDatabaseInstance("file://storage/postgres/migrations", "postgres", driver)
	if err != nil {
		return err
	}
	err = m.Up()
	if err == migrate.ErrNoChange {
		logrus.Debug("Database schema already up to date")
		err = nil
	}
	return err
}
```
We use migrate ver 3.2.0
We use [pq](https://github.com/lib/pq) driver

### PR DESCRIPTION
**Pull request by tsenart**
Fixes #55. Superseeds #149.

### CODE REVIEW

**Comment by tsenart** [comment]
Closed and reopened to trigger CI again which had a flake in the previous run.

File: database/postgres/postgres_test.go [hunk 1]
```diff
@@ -309,6 +309,35 @@ func TestPostgres_Lock(t *testing.T) {
...
+		}
+
+		db, err := sql.Open("postgres", pgConnectionString(ip, port))
+		if err != nil {
+			t.Fatal(err)
+		}
+		defer db.Close()
+
+		const concurrency = 30
+		ch := make(chan error, concurrency)
```
[the remark this answers is not in the document]
Comment (tsenart) [reply database/postgres/postgres_test.go]: OK, that's fine in this case since we can just call `t.Error` directly in the go routine.

File: database/postgres/postgres.go [hunk 2]
```diff
@@ -332,20 +332,19 @@ func (p *Postgres) Drop() error {
...
+	if err = p.Lock(); err != nil {
+		return err
 	}
 
-	// if not, create the empty migration table
-	query = `CREATE TABLE "` + p.config.MigrationsTable + `" (version bigint not null primary key, dirty boolean not null)`
-	if _, err := p.conn.ExecContext(context.Background(), query); err != nil {
+	defer func() {
+		if e := p.Unlock(); err == nil {
+			err = e
```
[the remark this answers is not in the document]
Comment (tsenart) [reply database/postgres/postgres.go]: The error wasn't being clobbered since it was only being set when the outer error was nil. But we were loosing the information of this error when the outer error was not nil. So wrapping is beneficial in this case. Any specific approach you prefer?

[the remark this answers is not in the document]
Comment (dhui) [reply database/postgres/postgres.go]: At a quick glance, it seems like "error values" topic is most applicable.

There are some [implementations of the draft](https://github.com/golang/go/wiki/Go2ErrorValuesFeedback#draft-implementation). Of those, I'd lean towards `golang.org/x/exp/errors` but I'm not feeling particularly bold...

[the remark this answers is not in the document]
Comment (tsenart) [reply database/postgres/postgres.go]: Marking as resolved based on my last commit. Let me know if it looks ok to you.

File: database/postgres/postgres.go [hunk 3]
```diff
@@ -332,20 +332,19 @@ func (p *Postgres) Drop() error {
...
+		}
+	}()
+
+	query := `CREATE TABLE IF NOT EXISTS "` + p.config.MigrationsTable + `" (version bigint not null primary key, dirty boolean not null)`
```
Comment (tsenart) [inline database/postgres/postgres.go]: A note about the introduction of "IF NOT EXISTS" here. Without it, but with the advisory lock in place, we get these errors, which makes sense: https://gist.github.com/tsenart/3cb026aa5705d7a2db14ddc610a2a8d2

However, as per Postgres' documentation, it seems we wouldn't support versions older than https://www.postgresql.org/docs/9.1/sql-createtable.html, which is when "CREATE IF NOT EXISTS" was introduced.

If that's not desirable, we can revert to use a SELECT first to check if the table exists and then run the CREATE if not, but all wrapped in an advisory lock.

Comment (tsenart) [reply database/postgres/postgres.go]: Answered my own question. Reverted back to using a SELECT first.

**Comment by tsenart** [comment]
@dhui: Please take another look!

File: database/postgres/postgres.go [hunk 4]
```diff
@@ -340,12 +340,28 @@ func (p *Postgres) ensureVersionTable() (err error) {
 	defer func() {
 		if e := p.Unlock(); err == nil {
 			err = e
+		} else if e != nil {
+			err = &database.Error{OrigErr: err, Err: e.Error()}
```
Comment (dhui) [inline database/postgres/postgres.go]: Don't use `database.Error` since it's meant to wrap database errors.
In this scenario, the appropriate usage of `database.Error` would be: `database.Error{OrigErr: e, Err: "Failed to unlock pg advisory lock while ensuring schema version table"}`, which should still reference any original error.

Comment (dhui) [inline database/postgres/postgres.go]: Don't use `database.Error` since it's meant to wrap database errors.
In this scenario, the appropriate usage of `database.Error` would be: `database.Error{OrigErr: e, Err: "Failed to unlock pg advisory lock while ensuring schema version table"}`, which should still reference any original error.

We should use another package for wrapping the original error. See previous discussion: https://github.com/golang-migrate/migrate/pull/150#discussion_r247308856

File: database/postgres/postgres.go [hunk 5]
```diff
@@ -340,12 +340,28 @@ func (p *Postgres) ensureVersionTable() (err error) {
...
 		}
 	}()
 
-	query := `CREATE TABLE IF NOT EXISTS "` + p.config.MigrationsTable + `" (version bigint not null primary key, dirty boolean not null)`
+	// We don't use a simple CREATE IF NOT EXISTS below because we want to support
```
Comment (dhui) [inline database/postgres/postgres.go]: Thanks for adding this documentation!

I'm fine dropping support for versions of postgres below 9.4 since they're not officially supported: https://www.postgresql.org/support/versioning/

I still need to update the postgres versions we test against...

File: database/postgres/postgres.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (tsenart) [reply database/postgres/postgres.go]: I have experience with https://github.com/pkg/errors and don't think we should rely on golang.org/x/exp/errors which is experimental at this stage. I'll make a change to use https://github.com/pkg/errors

[the remark this answers is not in the document]
Comment (tsenart) [reply database/postgres/postgres.go]: Looking at it better, these two errors are more like a multi error rather than a chain, since they both happen in the same stack frame. So I used https://github.com/hashicorp/go-multierror

File: database/postgres/postgres.go (hunk 5 above)
Comment (tsenart) [reply database/postgres/postgres.go]: OK. Let's keep it this way and once you update the versions of Postgres we test against, feel free to convert this to a CREATE IF NOT EXISTS.

Comment (tsenart) [reply database/postgres/postgres.go]: OK, I [just checked](https://github.com/golang-migrate/migrate/blob/master/database/postgres/postgres_test.go#L28) and it seems we no longer test with 9.0. I'll just revert this to use CREATE IF NOT EXISTS then.

**Comment by tsenart** [comment]
@dhui: Please take another look :-)

File: database/postgres/postgres.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (dhui) [reply database/postgres/postgres.go]: Using `hashicorp/go-multierror` sounds good.

You'll need to use [dep](https://github.com/golang/dep) to add a dependency on `github.com/hashicorp/go-multierror` for Go 1.10.x support. e.g. `dep ensure -add github.com/hashicorp/go-multierror@v1.0.0`

File: database/postgres/postgres.go [hunk 6]
```diff
@@ -332,21 +333,23 @@ func (p *Postgres) Drop() error {
...
 	}
 
-	// if not, create the empty migration table
-	query = `CREATE TABLE "` + p.config.MigrationsTable + `" (version bigint not null primary key, dirty boolean not null)`
-	if _, err := p.conn.ExecContext(context.Background(), query); err != nil {
+	defer func() {
+		if e := p.Unlock(); err == nil {
+			err = e
+		} else if e != nil {
+			err = multierror.Append(err, e)
```
Comment (dhui) [inline database/postgres/postgres.go]: It's unclear to me if `multierror.Append()` will work correctly if the first arg is `nil`.
I think it's safer to use logic like:
```golang
if e:= p.Unlock(); e != nil {
    if err == nil {
        err = e
    } else {
        err = multierror.Append(err, e)
    }
}
```

File: database/postgres/postgres.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (tsenart) [reply database/postgres/postgres.go]: Looking at this project's root directory, I see a `go.mod` and `go.sum`. Are we using `dep` as well? I'm confused.

[the remark this answers is not in the document]
Comment (dhui) [reply database/postgres/postgres.go]: > I'm confused.

Rightfully so!

I *believe* that Go 1.10.x does not support Go modules. Only Go 1.11+ does. Go 1.10.3 added support for interpreting `/vN` imports, but doesn't use `go.mod`, so we still need to use `dep` to manage dependencies for Go 1.10.x
See `.travis.yml` on how the split is done.

I have a test branch that removes `dep`, but the [Go 1.10.x run fails](https://travis-ci.org/dhui/migrate/builds/479586545) b/c `go.mod` is ignored.

Please correct me if I'm wrong or missing something.

File: database/postgres/postgres.go (hunk 6 above)
Comment (tsenart) [reply database/postgres/postgres.go]: > Also, the else if condition contains a hidden check for both the err and e variables.

What is a hidden check?

Comment (dhui) [reply database/postgres/postgres.go]: the `else if e != nil` is actually `if err == nil && e != nil` but isn't as readable since it's a single conditional checking 2 variables in different branches.

Comment (tsenart) [reply database/postgres/postgres.go]: That's what an else branch always does. In the extreme case, if we want to be super explicit, we'd do this:

```go
if x == 2 {
  // it's 2
} else if x != 2 {
  // not 2
}
```

But this is just style preference. So I'll re-write to your preferred approach.

File: database/postgres/postgres.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (tsenart) [reply database/postgres/postgres.go]: Makes sense to me. I'll fix, thanks for the explanation!

**Comment by tsenart** [comment]
@dhui: I added the dependency manually to Gopkg.toml but that didn't seem to work. Running `dep ensure -add github.com/hashicorp/go-multierror@v1.0.0` leads to errors: https://gist.github.com/tsenart/bad59caf9a41e55ea8347c43d2c11719

Not sure how to proceed. Please help :-)

**Comment by dhui** [comment]
Thanks for adding the dependency via `dep`.

> I added the dependency manually to Gopkg.toml

I pushed a new commit that updates Gopkg.lock to your repo branch. Once tests pass, I'll merge.

**Comment by dhui** [comment]
Will cut a new release in ~1 week
