### PR TITLE
Resolves #647 - Fixes typos in Mongo advisory locking parameters

### LINKED ISSUE #647: Typos in Mongo Parameters
**Describe the Bug**
The mongo documentation mispells the word timeout for timeout in a number of places

**Steps to Reproduce**
1. Open this [link](https://github.com/golang-migrate/migrate/blob/master/database/mongodb/mongodb.go#L140)
2. Copy the words between x-advisory-lock- and -interval
3. Paste it into wikitionary.

**Expected Behavior**
An english word.

### PR DESCRIPTION
**Pull request by SJrX**
`make-test` was failing a bunch for me on neo4j, and mssql, not sure if it's just my environment however. I can investigate if you think it's a risk.

This is for #647

### CODE REVIEW

File: database/mongodb/mongodb.go [hunk 1]
```diff
@@ -137,7 +137,16 @@ func (m *Mongo) Open(dsn string) (database.Driver, error) {
 	if err != nil {
 		return nil, err
 	}
-	maxLockingIntervals, err := parseInt(unknown.Get("x-advisory-lock-timout-interval"), DefaultLockTimeoutInterval)
+
+	lockTimeout := unknown.Get("x-advisory-lock-timeout-interval")
+
+	if lockTimeout == "" {
+		// The initial release had a typo for this argument but for backwards compatibility sake, we will keep supporting it.
+		lockTimeout = unknown.Get("x-advisory-lock-timout-interval")
```
Comment (dhui) [inline database/mongodb/mongodb.go:145]: Thanks for preserving the old behavior! Let's return an error explaining that only one should be specified if both are specified.

**Review by dhui — CHANGES_REQUESTED** [review]
Thanks for the find and fix!
I can't believe I missed this... 🤦 

Luckily this exact typo only occurs here!
```shell
$ git grep -l timout
database/mongodb/README.md
database/mongodb/mongodb.go
```

File: database/mongodb/mongodb.go (hunk 1 above)
Comment (dhui) [reply database/mongodb/mongodb.go:145]: This fix isn't urgent so can wait until you're back from vacation. Or I can make the change (based off of your change). I'd like to support existing users in a backwards compatible manner but also eliminate any confusion if both parameters are specified.

Comment (SJrX) [reply database/mongodb/mongodb.go]: Hows that @dhui ?

File: CONTRIBUTING.md [hunk 2]
```diff
@@ -11,7 +11,7 @@
   1. Write awesome code ...
   1. `make test` to run all tests against all database versions
   1. Push code and open Pull Request
- 
+ :wq
```
Comment (dhui) [inline CONTRIBUTING.md:14]: vim!

File: database/mongodb/mongodb.go [hunk 3]
```diff
@@ -36,8 +36,9 @@ const LockIndexName = "lock_unique_key"                  // the name of the inde
 const contextWaitTimeout = 5 * time.Second               // how long to wait for the request to mongo to block/wait for.
 
 var (
-	ErrNoDatabaseName = fmt.Errorf("no database name")
-	ErrNilConfig      = fmt.Errorf("no config")
+	ErrNoDatabaseName        = fmt.Errorf("no database name")
+	ErrNilConfig             = fmt.Errorf("no config")
+	ErrTypoAndNotNonTypoUsed = fmt.Errorf("both x-advisory-lock-timeout-interval and x-advisory-lock-timout-interval were specified")
```
Comment (dhui) [inline database/mongodb/mongodb.go:41]: Since this is an exported specific error, let's make the name specific as well. e.g. something along the lines of: `ErrLockTimeoutConfigConflict`

**Review by dhui — CHANGES_REQUESTED** [review]
Thanks for addressing my feedback!

A couple minor things to fix and and we should be good to merge.

File: database/mongodb/mongodb.go (hunk 3 above)
Comment (SJrX) [reply database/mongodb/mongodb.go]: Done

File: CONTRIBUTING.md (hunk 2 above)
Comment (SJrX) [reply CONTRIBUTING.md]: Fixed

**Review by dhui — APPROVED** [review]
Thanks again for the find, fix, and addressing of feedback!
